### ISSUE TITLE
Can't compile anymore on MacOS X

### ISSUE THREAD

**Issue by vdiem** [numworks/epsilon#989]
Working on MacOS High Sierra (version 10.13.6), the build process was working properly, but since an update, it is now broken, and I can't figure why.

Can someone give me some hints ? Here is a reproduction of the error messages : 

$ make PLATFORM=simulator
I18N    apps/i18n.cpp
QSTRDAT python/port/genhdr/qstrdefs.generated.h
CXX     apps/main.o
In file included from ./apps/graph/graph/preimage_parameter_controller.h:5,
                 from ./apps/graph/graph/calculation_parameter_controller.h:6,
                 from ./apps/graph/graph/curve_parameter_controller.h:5,
                 from ./apps/graph/graph/graph_controller.h:7,
                 from ./apps/graph/app.h:6,
                 from <command-line>:
./apps/graph/graph/preimage_graph_controller.h: In member function 'virtual const char* Graph::PreimageGraphController::title()':
./apps/graph/graph/preimage_graph_controller.h:15:73: error: 'Preimage' is not a member of 'I18n::Message'
   const char * title() override { return I18n::translate(I18n::Message::Preimage); }
                                                                         ^~~~~~~~
In file included from ./apps/graph/list/list_controller.h:5,
                 from ./apps/graph/app.h:7,
                 from <command-line>:
./apps/graph/list/list_parameter_controller.h: In constructor 'Graph::ListParameterController::ListParameterController(Graph::ListController*, Responder*, I18n::Message, I18n::Message, SelectableTableViewDelegate*)':
./apps/graph/list/list_parameter_controller.h:15:33: error: 'Rename' is not a member of 'I18n::Message'
     m_renameCell(I18n::Message::Rename)
                                 ^~~~~~
make: *** [build/simulator/apps/main.o] Error 1

**Comment by Ecco** [comment]
I'm sorry but I can't reproduce this. Are you sure you're on the lasest revision and don't have any local modification? You could also try to do a clean build (`make clean`).

**Comment by EmilieNumworks** [comment]
Make sure you don't have a file apps/i18n.cpp and apps/i18n.h. If so, remove them before building. I am not sure if they are removed by the `make clean` (they should). They are now built in build/[PLATFORM]/ directory but if if old ones are in the epsilon directory, they might be used over the new ones in build/[PLATFORM]/ ...

**Comment by vdiem** [comment]
Hello Émilie,

Yes, well done, that was the problem. I removed the two files and it compiled. They were not removed by "make PLATFORM=simulator clean » because I tried many times.

But, I still have a problem at link :

ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
Undefined symbols for architecture x86_64:
  "_FT_Init_FreeType", referenced from:
      _main in ccTvvL2l.o
  "_FT_Load_Char", referenced from:
      _main in ccTvvL2l.o
  "_FT_New_Face", referenced from:
      _main in ccTvvL2l.o
  "_FT_Set_Pixel_Sizes", referenced from:
      _main in ccTvvL2l.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [build/simulator/kandinsky/fonts/rasterizer] Error 1

Any Idea ?
Regards,

Vincent
