### ISSUE TITLE
bad types on compilation

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#211]
Hello I tried to compile with Python 2.7.4 and I have several errors in `kandinsky/fonts/rasterizer.c`:

- format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘wchar_t’
- format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘unsigned int’

Also `/bin/sh: 1: clang++: not found` (which makes me think I miss something)

I recall that I never programmed in C++ nor in make, but the two first errors seem to be real errors unless I have the bad cpp  version (4.8.4)

Also with just make (without any target) I have

- apps/calculation/calculation.cpp:14:25: error: incompatible types in assignment of 'const char [1]' to 'char [100]'

**Comment by ian-abbott** [comment]
The "format '%x' expects ..." messages are probably fairly harmless. I couldn't reproduce them on my systems.

The `make PLATFORM=simulator` build currrently requires the "clang" compiler (although it looks like @Ecco is trying to change that).

The `make PLATFORM=device` (default) build fails to compile "apps/calculation/calculation.cpp" with older versions of arm-none-eabi-g++. You can check your version with the following command:

    arm-none-eabi-g++ --version

For example, the 4.9.3 version from Ubuntu 16.04 doesn't work (but it is possible to install an updated version from a PPA repository - See https://github.com/numworks/epsilon/issues/175#issuecomment-333509554).

**Comment by AlainBusser** [comment]
OK I managed to work with the fltk simulator. As I didn't find out how to modify netbeans's make targets, I have to compile by hand with the target "simulator" every time netbeans compiled. But it works so I close this issue :smile:
